const express = require("express")
const accountCreation = require("../controller/account-controller")
const login = require("../controller/login-controller")
const verifyToken = require("../middleware/verify-token")
const transferFunds = require("../controller/transaction-management/transfer-funds")
const balanceCheck = require("../controller/transaction-management/check-balance")
const verifyUser = require("../controller/transaction-management/verify-user")
const depositFunds = require("../controller/transaction-management/deposit-funds")
const withdrawFunds = require("../controller/transaction-management/withdraw-funds")
const changePassword = require("../controller/security-settings/change-password")
const resetPasswordLink = require("../controller/security-settings/reset-password-link")
const resetPasswordVerifyToken = require("../controller/security-settings/reset-password-token")
const resetPasswrd = require("../controller/security-settings/reset-passwrd")
const reset = require("../controller/security-settings/reset-passwrd")
const router = express.Router()

router.post("/create-account", accountCreation)
router.post("/login", login)
router.post("/reset-link", resetPasswordLink)
router.get("/verify-token/:token", resetPasswordVerifyToken)
router.post("/reset-password", reset)

router.use(verifyToken)
router.post("/transfers", transferFunds)
router.post("/verify-user", verifyUser)
router.get("/check-balance", balanceCheck)
router.post("/deposit-funds", depositFunds)
router.post("/withdraw-funds", withdrawFunds)
router.post("/change-password", changePassword)


module.exports = router